In [1]:
import pandas as pd
import numpy as np

In [2]:
procurement = pd.read_csv("../data/raw/Procurement KPI Analysis Dataset.csv")

In [3]:
procurement.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,NaN,Yes
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No

In [4]:
procurement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PO_ID             777 non-null    object
 1   Supplier          777 non-null    object
 2   Order_Date        777 non-null    object
 3   Delivery_Date     690 non-null    object
 4   Item_Category     777 non-null    object
 5   Order_Status      777 non-null    object
 6   Quantity          777 non-null    int64
 7   Unit_Price        777 non-null    float64
 8   Negotiated_Price  777 non-null    float64
 9   Defective_Units   641 non-null    float64
 10  Compliance        777 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 66.9+ KB

In [5]:
procurement.shape

(777, 11)

In [6]:
procurement.isnull().sum()

PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

In [7]:
procurement.describe()

          Quantity  Unit_Price  Negotiated_Price  Defective_Units
count   777.000000  777.000000        777.000000       641.000000
mean   1094.660232   58.283822         53.660721        74.803432
std     647.844551   28.101315         26.094930        69.187870
min      51.000000   10.840000          9.270000         0.000000
25%     615.000000   33.290000         30.460000        26.000000
50%    1075.000000   58.950000         53.800000        49.000000
75%    1548.000000   83.130000         76.550000       100.000000
max    5000.000000  109.170000        107.390000       321.000000

In [8]:
procurement_clean = procurement.copy()

In [9]:
procurement_clean.dtypes

PO_ID                object
Supplier             object
Order_Date           object
Delivery_Date        object
Item_Category        object
Order_Status         object
Quantity              int64
Unit_Price          float64
Negotiated_Price    float64
Defective_Units     float64
Compliance           object
dtype: object

In [10]:
procurement_clean['Order_Date'] = pd.to_datetime(procurement_clean['Order_Date'])

procurement_clean['Delivery_Date'] = pd.to_datetime(procurement_clean['Delivery_Date'])

In [11]:
procurement_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PO_ID             777 non-null    object
 1   Supplier          777 non-null    object
 2   Order_Date        777 non-null    datetime64[ns]
 3   Delivery_Date     690 non-null    datetime64[ns]
 4   Item_Category     777 non-null    object
 5   Order_Status      777 non-null    object
 6   Quantity          777 non-null    int64
 7   Unit_Price        777 non-null    float64
 8   Negotiated_Price  777 non-null    float64
 9   Defective_Units   641 non-null    float64
 10  Compliance        777 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(1), object(5)
memory usage: 66.9+ KB

In [12]:
procurement_clean['PO_ID'].duplicated().sum()

np.int64(0)

In [13]:
procurement_clean.duplicated().sum()

np.int64(0)

In [14]:
procurement_clean['Delivery_Missing'] = procurement_clean['Delivery_Date'].isnull()

In [15]:
procurement_clean['Defective_Units'] = procurement_clean['Defective_Units'].fillna(0)

In [16]:
procurement_clean.isnull().sum()

PO_ID                0
Supplier             0
Order_Date           0
Delivery_Date       87
Item_Category        0
Order_Status         0
Quantity             0
Unit_Price           0
Negotiated_Price     0
Defective_Units      0
Compliance           0
Delivery_Missing     0
dtype: int64

In [17]:
text_columns = ['Supplier', 'Item_Category', 'Order_Status', 'Compliance']

for col in text_columns:
    procurement_clean[col] = procurement_clean[col].str.strip().str.upper()

In [18]:
procurement_clean['Delivery_Delay_Days'] = (
    procurement_clean['Delivery_Date'] - procurement_clean['Order_Date']
).dt.days

In [19]:
procurement_clean['Savings_Per_Unit'] = (
    procurement_clean['Unit_Price'] - procurement_clean['Negotiated_Price']
)

procurement_clean['Total_Savings'] = (
    procurement_clean['Savings_Per_Unit'] * procurement_clean['Quantity']
)

In [20]:
procurement_clean['Defect_Rate'] = (
    procurement_clean['Defective_Units'] / procurement_clean['Quantity']
)

In [21]:
procurement_clean.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance,Delivery_Missing,Delivery_Delay_Days,Savings_Per_Unit,Total_Savings,Defect_Rate
0,PO-00001,ALPHA_INC,2023-10-17,2023-10-25,OFFICE SUPPLIES,CANCELLED,1176,20.13,17.81,0.0,YES,False,8.0,2.32,2728.32,0.000000
1,PO-00002,DELTA_LOGISTICS,2022-04-25,2022-05-05,OFFICE SUPPLIES,DELIVERED,1509,39.32,37.34,235.0,YES,False,10.0,1.98,2987.82,0.155732
2,PO-00003,GAMMA_CO,2022-01-26,2022-02-15,MRO,DELIVERED,910,95.51,92.26,41.0,YES,False,20.0,3.25,2957.50,0.045055
3,PO-00004,BETA_SUPPLIES,2022-10-09,2022-10-28,PACKAGING,DELIVERED,1344,99.85,95.52,112.0,YES,False,19.0,4.33,5819.52,0.083333
4,PO-00005,DELTA_LOGISTICS,2022-09-08,2022-09-20,RAW MATERIALS,DELIVERED,1180,64.07,60.53,171.0,NO,False,12.0,3.54,4177.20,0.144915

In [22]:
procurement_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PO_ID                777 non-null    object
 1   Supplier             777 non-null    object
 2   Order_Date           777 non-null    datetime64[ns]
 3   Delivery_Date        690 non-null    datetime64[ns]
 4   Item_Category        777 non-null    object
 5   Order_Status         777 non-null    object
 6   Quantity             777 non-null    int64
 7   Unit_Price           777 non-null    float64
 8   Negotiated_Price     777 non-null    float64
 9   Defective_Units      777 non-null    float64
 10  Compliance           777 non-null    object
 11  Delivery_Missing     777 non-null    bool
 12  Delivery_Delay_Days  690 non-null    float64
 13  Savings_Per_Unit     777 non-null    float64
 14  Total_Savings        777 non-null    float64
 15  Defect_Rate          777 non-null    float64
dtypes: bool(1), datetime64[ns](2), float64(7), int64(1), object(5)
memory usage: 91.9+ KB

In [23]:
procurement_clean.to_csv(
    "../data/cleaned/cleaned_procurement.csv",
    index=False
)

In [24]:
purchases = pd.read_csv("../data/raw/purchases.csv")

In [25]:
purchases.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [26]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   VendorNumber    int64
 6   VendorName      object
 7   PONumber        int64
 8   PODate          object
 9   ReceivingDate   object
 10  InvoiceDate     object
 11  PayDate         object
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: float64(2), int64(6), object(8)
memory usage: 289.6+ MB

In [27]:
purchases.shape

(2372474, 16)

In [28]:
purchases.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              3
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [29]:
purchases.describe()

,Store,Brand,VendorNumber,PONumber,PurchasePrice,Quantity,Dollars,Classification
count,2.372474e+06,2.372474e+06,2.372474e+06,2.372474e+06,2.372474e+06,2.372474e+06,2.372474e+06,2.372474e+06
mean,4.465133e+01,1.241864e+04,6.886436e+03,1.104094e+04,1.205005e+01,1.415585e+01,1.356815e+02,1.443520e+00
std,2.351245e+01,1.255728e+04,8.066694e+03,1.565340e+03,1.794510e+01,2.344616e+01,2.816649e+02,4.967999e-01
min,1.000000e+00,5.800000e+01,2.000000e+00,8.106000e+03,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00
25%,2.500000e+01,3.639000e+03,3.252000e+03,9.761000e+03,6.120000e+00,6.000000e+00,4.926000e+01,1.000000e+00
50%,4.800000e+01,6.523000e+03,4.425000e+03,1.110300e+04,9.220000e+00,1.000000e+01,8.393000e+01,1.000000e+00
75%,6.700000e+01,1.887700e+04,9.552000e+03,1.239700e+04,1.449000e+01,1.200000e+01,1.405200e+02,2.000000e+00
max,8.100000e+01,9.063100e+04,2.013590e+05,1.366100e+04,5.681810e+03,3.816000e+03,5.017570e+04,2.000000e+00

In [30]:
purchases_clean = purchases.copy()

In [31]:
date_columns = ['PODate', 'ReceivingDate', 'InvoiceDate', 'PayDate']

for col in date_columns:
    purchases_clean[col] = pd.to_datetime(purchases_clean[col])

In [32]:
purchases_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   VendorNumber    int64
 6   VendorName      object
 7   PONumber        int64
 8   PODate          datetime64[ns]
 9   ReceivingDate   datetime64[ns]
 10  InvoiceDate     datetime64[ns]
 11  PayDate         datetime64[ns]
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: datetime64[ns](4), float64(2), int64(6), object(4)
memory usage: 289.6+ MB

In [33]:
purchases_clean['Size'] = purchases_clean['Size'].fillna('UNKNOWN')

In [34]:
text_columns = ['Description', 'VendorName', 'Size']

for col in text_columns:
    purchases_clean[col] = purchases_clean[col].str.strip().str.upper()

In [35]:
purchases_clean.duplicated().sum()

np.int64(0)

In [36]:
purchases_clean['Lead_Time_Days'] = (
    purchases_clean['ReceivingDate'] - purchases_clean['PODate']
).dt.days

In [37]:
purchases_clean['Invoice_Processing_Days'] = (
    purchases_clean['InvoiceDate'] - purchases_clean['ReceivingDate']
).dt.days

In [38]:
purchases_clean['Payment_Cycle_Days'] = (
    purchases_clean['PayDate'] - purchases_clean['InvoiceDate']
).dt.days

In [39]:
purchases_clean['Unit_Cost'] = (
    purchases_clean['Dollars'] / purchases_clean['Quantity']
)

In [40]:
purchases_clean.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification,Lead_Time_Days,Invoice_Processing_Days,Payment_Cycle_Days,Unit_Cost
0,69_MOUNTMEND_8412,69,8412,TEQUILA OCHO PLATA FRESNO,750ML,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1,12,2,43,35.71
1,30_CULCHETH_5255,30,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1,10,6,45,9.35
2,34_PITMERDEN_5215,34,5215,TGI FRIDAYS LONG ISLAND ICED,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1,11,5,45,9.41
3,1_HARDERSFIELD_5255,1,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1,10,6,45,9.35
4,76_DONCASTER_2034,76,2034,GLENDALOUGH DOUBLE BARREL,750ML,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1,9,7,38,21.32

In [41]:
purchases_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 20 columns):
 #   Column                   Dtype
---  ------                   -----
 0   InventoryId              object
 1   Store                    int64
 2   Brand                    int64
 3   Description              object
 4   Size                     object
 5   VendorNumber             int64
 6   VendorName               object
 7   PONumber                 int64
 8   PODate                   datetime64[ns]
 9   ReceivingDate            datetime64[ns]
 10  InvoiceDate              datetime64[ns]
 11  PayDate                  datetime64[ns]
 12  PurchasePrice            float64
 13  Quantity                 int64
 14  Dollars                  float64
 15  Classification           int64
 16  Lead_Time_Days           int64
 17  Invoice_Processing_Days  int64
 18  Payment_Cycle_Days       int64
 19  Unit_Cost                float64
dtypes: datetime64[ns](4), float64(3), int64(9), object(4)
memory usage: 362.0+ MB

In [42]:
purchases_clean.to_csv(
    "../data/cleaned/cleaned_purchases.csv",
    index=False
)