In [1]:
import pandas as pd
import numpy as np

In [2]:
purchases = pd.read_csv(
    "../data/cleaned/cleaned_purchases.csv"
)

In [3]:
purchases.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification,Lead_Time_Days,Invoice_Processing_Days,Payment_Cycle_Days,Unit_Cost
0,69_MOUNTMEND_8412,69,8412,TEQUILA OCHO PLATA FRESNO,750ML,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1,12,2,43,35.71
1,30_CULCHETH_5255,30,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1,10,6,45,9.35
2,34_PITMERDEN_5215,34,5215,TGI FRIDAYS LONG ISLAND ICED,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1,11,5,45,9.41
3,1_HARDERSFIELD_5255,1,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1,10,6,45,9.35
4,76_DONCASTER_2034,76,2034,GLENDALOUGH DOUBLE BARREL,750ML,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1,9,7,38,21.32

In [4]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 20 columns):
 #   Column                   Dtype
---  ------                   -----
 0   InventoryId              object
 1   Store                    int64
 2   Brand                    int64
 3   Description              object
 4   Size                     object
 5   VendorNumber             int64
 6   VendorName               object
 7   PONumber                 int64
 8   PODate                   object
 9   ReceivingDate            object
 10  InvoiceDate              object
 11  PayDate                  object
 12  PurchasePrice            float64
 13  Quantity                 int64
 14  Dollars                  float64
 15  Classification           int64
 16  Lead_Time_Days           int64
 17  Invoice_Processing_Days  int64
 18  Payment_Cycle_Days       int64
 19  Unit_Cost                float64
dtypes: float64(3), int64(9), object(8)
memory usage: 362.0+ MB

In [5]:
date_columns = [
    'PODate',
    'ReceivingDate',
    'InvoiceDate',
    'PayDate'
]

for col in date_columns:
    purchases[col] = pd.to_datetime(purchases[col])

In [6]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 20 columns):
 #   Column                   Dtype
---  ------                   -----
 0   InventoryId              object
 1   Store                    int64
 2   Brand                    int64
 3   Description              object
 4   Size                     object
 5   VendorNumber             int64
 6   VendorName               object
 7   PONumber                 int64
 8   PODate                   datetime64[ns]
 9   ReceivingDate            datetime64[ns]
 10  InvoiceDate              datetime64[ns]
 11  PayDate                  datetime64[ns]
 12  PurchasePrice            float64
 13  Quantity                 int64
 14  Dollars                  float64
 15  Classification           int64
 16  Lead_Time_Days           int64
 17  Invoice_Processing_Days  int64
 18  Payment_Cycle_Days       int64
 19  Unit_Cost                float64
dtypes: datetime64[ns](4), float64(3), int64(9), object(4)
memory usage: 362.0+ MB

In [7]:
monthly_spend = (
    purchases.groupby(
        purchases['PODate'].dt.to_period('M')
    )['Dollars']
    .sum()
    .reset_index()
)

monthly_spend['PODate'] = monthly_spend['PODate'].astype(str)

monthly_spend

     PODate      Dollars
0   2023-12   6950117.22
1   2024-01  19138815.42
2   2024-02  20147364.53
3   2024-03  20252968.80
4   2024-04  21798729.53
5   2024-05  28693060.33
6   2024-06  29699192.07
7   2024-07  32193842.50
8   2024-08  30747883.70
9   2024-09  26840919.81
10  2024-10  31836531.74
11  2024-11  27252267.02
12  2024-12  26349072.86

In [8]:
monthly_spend.head()

    PODate      Dollars
0  2023-12   6950117.22
1  2024-01  19138815.42
2  2024-02  20147364.53
3  2024-03  20252968.80
4  2024-04  21798729.53

In [9]:
monthly_spend['Previous_Month_Spend'] = (
    monthly_spend['Dollars'].shift(1)
)

monthly_spend

     PODate      Dollars  Previous_Month_Spend
0   2023-12   6950117.22                   NaN
1   2024-01  19138815.42            6950117.22
2   2024-02  20147364.53           19138815.42
3   2024-03  20252968.80           20147364.53
4   2024-04  21798729.53           20252968.80
5   2024-05  28693060.33           21798729.53
6   2024-06  29699192.07           28693060.33
7   2024-07  32193842.50           29699192.07
8   2024-08  30747883.70           32193842.50
9   2024-09  26840919.81           30747883.70
10  2024-10  31836531.74           26840919.81
11  2024-11  27252267.02           31836531.74
12  2024-12  26349072.86           27252267.02

In [10]:
monthly_spend['Rolling_3Month_Avg'] = (
    monthly_spend['Dollars']
    .rolling(window=3)
    .mean()
)

monthly_spend

     PODate      Dollars  Previous_Month_Spend  Rolling_3Month_Avg
0   2023-12   6950117.22                   NaN                 NaN
1   2024-01  19138815.42            6950117.22                 NaN
2   2024-02  20147364.53           19138815.42        1.541210e+07
3   2024-03  20252968.80           20147364.53        1.984638e+07
4   2024-04  21798729.53           20252968.80        2.073302e+07
5   2024-05  28693060.33           21798729.53        2.358159e+07
6   2024-06  29699192.07           28693060.33        2.673033e+07
7   2024-07  32193842.50           29699192.07        3.019536e+07
8   2024-08  30747883.70           32193842.50        3.088031e+07
9   2024-09  26840919.81           30747883.70        2.992755e+07
10  2024-10  31836531.74           26840919.81        2.980845e+07
11  2024-11  27252267.02           31836531.74        2.864324e+07
12  2024-12  26349072.86           27252267.02        2.847929e+07

In [11]:
monthly_spend['Spend_Growth_Rate'] = (
    monthly_spend['Dollars']
    .pct_change()
)

monthly_spend

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate
0,2023-12,6950117.22,NaN,NaN,NaN
1,2024-01,19138815.42,6950117.22,NaN,1.753740
2,2024-02,20147364.53,19138815.42,1.541210e+07,0.052697
3,2024-03,20252968.80,20147364.53,1.984638e+07,0.005242
4,2024-04,21798729.53,20252968.80,2.073302e+07,0.076323
5,2024-05,28693060.33,21798729.53,2.358159e+07,0.316272
6,2024-06,29699192.07,28693060.33,2.673033e+07,0.035065
7,2024-07,32193842.50,29699192.07,3.019536e+07,0.083997
8,2024-08,30747883.70,32193842.50,3.088031e+07,-0.044914
9,2024-09,26840919.81,30747883.70,2.992755e+07,-0.127064
10,2024-10,31836531.74,26840919.81,2.980845e+07,0.186119
11,2024-11,27252267.02,31836531.74,2.864324e+07,-0.143994
12,2024-12,26349072.86,27252267.02,2.847929e+07,-0.033142

In [12]:
monthly_spend.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate
0,2023-12,6950117.22,NaN,NaN,NaN
1,2024-01,19138815.42,6950117.22,NaN,1.753740
2,2024-02,20147364.53,19138815.42,1.541210e+07,0.052697
3,2024-03,20252968.80,20147364.53,1.984638e+07,0.005242
4,2024-04,21798729.53,20252968.80,2.073302e+07,0.076323

In [1]:
import pandas as pd

df = pd.read_csv("../data/cleaned/cleaned_purchases.csv")

df['PODate'] = pd.to_datetime(df['PODate'])
df.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification,Lead_Time_Days,Invoice_Processing_Days,Payment_Cycle_Days,Unit_Cost
0,69_MOUNTMEND_8412,69,8412,TEQUILA OCHO PLATA FRESNO,750ML,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1,12,2,43,35.71
1,30_CULCHETH_5255,30,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1,10,6,45,9.35
2,34_PITMERDEN_5215,34,5215,TGI FRIDAYS LONG ISLAND ICED,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1,11,5,45,9.41
3,1_HARDERSFIELD_5255,1,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1,10,6,45,9.35
4,76_DONCASTER_2034,76,2034,GLENDALOUGH DOUBLE BARREL,750ML,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1,9,7,38,21.32

In [2]:
df['Month'] = df['PODate'].dt.to_period('M')

In [4]:
df = pd.read_csv("../data/cleaned/cleaned_procurement.csv")
df.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance,Delivery_Missing,Delivery_Delay_Days,Savings_Per_Unit,Total_Savings,Defect_Rate
0,PO-00001,ALPHA_INC,2023-10-17,2023-10-25,OFFICE SUPPLIES,CANCELLED,1176,20.13,17.81,0.0,YES,False,8.0,2.32,2728.32,0.000000
1,PO-00002,DELTA_LOGISTICS,2022-04-25,2022-05-05,OFFICE SUPPLIES,DELIVERED,1509,39.32,37.34,235.0,YES,False,10.0,1.98,2987.82,0.155732
2,PO-00003,GAMMA_CO,2022-01-26,2022-02-15,MRO,DELIVERED,910,95.51,92.26,41.0,YES,False,20.0,3.25,2957.50,0.045055
3,PO-00004,BETA_SUPPLIES,2022-10-09,2022-10-28,PACKAGING,DELIVERED,1344,99.85,95.52,112.0,YES,False,19.0,4.33,5819.52,0.083333
4,PO-00005,DELTA_LOGISTICS,2022-09-08,2022-09-20,RAW MATERIALS,DELIVERED,1180,64.07,60.53,171.0,NO,False,12.0,3.54,4177.20,0.144915

In [5]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['Month'] = df['Order_Date'].dt.to_period('M')

In [6]:
category_monthly = df.groupby(['Item_Category', 'Month'])['Quantity'].sum().reset_index()

category_monthly['Month'] = category_monthly['Month'].astype(str)

category_monthly.head()

  Item_Category    Month  Quantity
0   ELECTRONICS  2022-01     10546
1   ELECTRONICS  2022-02      5052
2   ELECTRONICS  2022-03      9321
3   ELECTRONICS  2022-04     13349
4   ELECTRONICS  2022-05      5322

In [7]:
category_monthly = category_monthly.sort_values(['Item_Category', 'Month'])

In [8]:
# approximate spend using average unit cost assumption
category_monthly['Avg_Unit_Cost'] = df.groupby(['Item_Category'])['Unit_Price'].transform('mean')

category_monthly['Dollars'] = category_monthly['Quantity'] * category_monthly['Avg_Unit_Cost']

In [9]:
category_monthly['Lag_1'] = category_monthly.groupby('Item_Category')['Dollars'].shift(1)
category_monthly['Lag_2'] = category_monthly.groupby('Item_Category')['Dollars'].shift(2)
category_monthly['Rolling_3'] = category_monthly.groupby('Item_Category')['Dollars'].rolling(3).mean().reset_index(level=0, drop=True)

In [10]:
category_monthly['Target'] = category_monthly.groupby('Item_Category')['Dollars'].shift(-1)

In [11]:
category_monthly = category_monthly.dropna().reset_index(drop=True)

In [12]:
category_monthly = pd.get_dummies(category_monthly, columns=['Item_Category'], drop_first=True)

In [13]:
X = category_monthly.drop(columns=['Target', 'Month'])
y = category_monthly['Target']

In [14]:
split = int(len(category_monthly) * 0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [16]:
y_pred = model.predict(X_test)

In [17]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MAE: 149509.5923290668
R2: -0.28277024891993796

In [19]:
df['Month'] = df['Month'].dt.to_timestamp()

In [20]:
df = df.sort_values(['Item_Category', 'Month'])

In [21]:
df = df.sort_values(['Item_Category', 'Month'])
df['Month'] = pd.to_datetime(df['Month'])

In [22]:
df['Lag_1'] = df.groupby('Item_Category')['Quantity'].shift(1)
df['Lag_2'] = df.groupby('Item_Category')['Quantity'].shift(2)
df['Lag_3'] = df.groupby('Item_Category')['Quantity'].shift(3)

In [23]:
df['Rolling_3'] = df.groupby('Item_Category')['Quantity'].transform(
    lambda x: x.rolling(3).mean()
)

df['Rolling_6'] = df.groupby('Item_Category')['Quantity'].transform(
    lambda x: x.rolling(6).mean()
)

In [24]:
df['Prev_Month'] = df.groupby('Item_Category')['Quantity'].shift(1)

df['Growth_Rate'] = (df['Quantity'] - df['Prev_Month']) / df['Prev_Month']

In [25]:
df_model = df.dropna().reset_index(drop=True)

In [26]:
df_model['Time_Index'] = df_model.groupby('Item_Category').cumcount()

In [27]:
features = [
    'Lag_1',
    'Lag_2',
    'Lag_3',
    'Rolling_3',
    'Rolling_6',
    'Growth_Rate',
    'Time_Index'
]

In [28]:
target = 'Quantity'

In [29]:
train_size = int(len(df_model) * 0.8)

train = df_model.iloc[:train_size]
test = df_model.iloc[train_size:]

In [30]:
df_model.columns

Index(['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category',
       'Order_Status', 'Quantity', 'Unit_Price', 'Negotiated_Price',
       'Defective_Units', 'Compliance', 'Delivery_Missing',
       'Delivery_Delay_Days', 'Savings_Per_Unit', 'Total_Savings',
       'Defect_Rate', 'Month', 'Lag_1', 'Lag_2', 'Lag_3', 'Rolling_3',
       'Rolling_6', 'Prev_Month', 'Growth_Rate', 'Time_Index'],
      dtype='object')

In [32]:
train.isnull().sum().sum()
test.isnull().sum().sum()

np.int64(0)

In [33]:
train['Month'].max(), test['Month'].min()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2022-02-01 00:00:00'))

In [34]:
train.shape, test.shape

((533, 25), (134, 25))

In [35]:
df_model = df_model.sort_values('Month')

In [36]:
df_model['Month'].min(), df_model['Month'].max()

(Timestamp('2022-01-01 00:00:00'), Timestamp('2024-01-01 00:00:00'))

In [37]:
train_size = int(len(df_model) * 0.8)

train = df_model.iloc[:train_size]
test = df_model.iloc[train_size:]

In [38]:
train['Month'].max(), test['Month'].min()

(Timestamp('2023-08-01 00:00:00'), Timestamp('2023-08-01 00:00:00'))

In [39]:
df_model = df_model.sort_values('Month')

In [40]:
df_model['Month'].min(), df_model['Month'].max()

(Timestamp('2022-01-01 00:00:00'), Timestamp('2024-01-01 00:00:00'))

In [41]:
cutoff = df_model['Month'].quantile(0.8)

In [42]:
train = df_model[df_model['Month'] <= cutoff]
test = df_model[df_model['Month'] > cutoff]

In [43]:
train['Month'].max(), test['Month'].min()

(Timestamp('2023-08-01 00:00:00'), Timestamp('2023-09-01 00:00:00'))