In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv( "../data/cleaned/monthly_spend_features.csv")
df.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate
0,2024-02,20147364.53,19138815.42,1.541210e+07,0.052697
1,2024-03,20252968.80,20147364.53,1.984638e+07,0.005242
2,2024-04,21798729.53,20252968.80,2.073302e+07,0.076323
3,2024-05,28693060.33,21798729.53,2.358159e+07,0.316272
4,2024-06,29699192.07,28693060.33,2.673033e+07,0.035065

In [5]:
df.columns

Index(['PODate', 'Dollars', 'Previous_Month_Spend', 'Rolling_3Month_Avg',
       'Spend_Growth_Rate'],
      dtype='object')

In [6]:
df['PODate'] = pd.to_datetime(df['PODate'], errors='coerce')

df = df.sort_values('PODate')

df.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate
0,2024-02-01,20147364.53,19138815.42,1.541210e+07,0.052697
1,2024-03-01,20252968.80,20147364.53,1.984638e+07,0.005242
2,2024-04-01,21798729.53,20252968.80,2.073302e+07,0.076323
3,2024-05-01,28693060.33,21798729.53,2.358159e+07,0.316272
4,2024-06-01,29699192.07,28693060.33,2.673033e+07,0.035065

In [7]:
df['MoM_Growth_%'] = df['Dollars'].pct_change() * 100

df['Rolling_3'] = df['Dollars'].rolling(3).mean()

df['Rolling_6'] = df['Dollars'].rolling(6).mean()

df.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate,MoM_Growth_%,Rolling_3,Rolling_6
0,2024-02-01,20147364.53,19138815.42,1.541210e+07,0.052697,NaN,NaN,NaN
1,2024-03-01,20252968.80,20147364.53,1.984638e+07,0.005242,0.524159,NaN,NaN
2,2024-04-01,21798729.53,20252968.80,2.073302e+07,0.076323,7.632267,2.073302e+07,NaN
3,2024-05-01,28693060.33,21798729.53,2.358159e+07,0.316272,31.627214,2.358159e+07,NaN
4,2024-06-01,29699192.07,28693060.33,2.673033e+07,0.035065,3.506533,2.673033e+07,NaN

In [11]:
df.columns

Index(['PODate', 'Dollars', 'Previous_Month_Spend', 'Rolling_3Month_Avg',
       'Spend_Growth_Rate', 'MoM_Growth_%', 'Rolling_3', 'Rolling_6'],
      dtype='object')

In [12]:
df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PODate                11 non-null     datetime64[ns]
 1   Dollars               11 non-null     float64
 2   Previous_Month_Spend  11 non-null     float64
 3   Rolling_3Month_Avg    11 non-null     float64
 4   Spend_Growth_Rate     11 non-null     float64
 5   MoM_Growth_%          10 non-null     float64
 6   Rolling_3             9 non-null      float64
 7   Rolling_6             6 non-null      float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 836.0 bytes

In [13]:
df['Forecast_Trend'] = df['Dollars'].pct_change() * 100

df['Forecast_Trend'] = df['Forecast_Trend'].round(2)

df.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate,MoM_Growth_%,Rolling_3,Rolling_6,Forecast_Trend
0,2024-02-01,20147364.53,19138815.42,1.541210e+07,0.052697,NaN,NaN,NaN,NaN
1,2024-03-01,20252968.80,20147364.53,1.984638e+07,0.005242,0.524159,NaN,NaN,0.52
2,2024-04-01,21798729.53,20252968.80,2.073302e+07,0.076323,7.632267,2.073302e+07,NaN,7.63
3,2024-05-01,28693060.33,21798729.53,2.358159e+07,0.316272,31.627214,2.358159e+07,NaN,31.63
4,2024-06-01,29699192.07,28693060.33,2.673033e+07,0.035065,3.506533,2.673033e+07,NaN,3.51

In [14]:
forecast_metrics = df.copy()

forecast_metrics.head()

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate,MoM_Growth_%,Rolling_3,Rolling_6,Forecast_Trend
0,2024-02-01,20147364.53,19138815.42,1.541210e+07,0.052697,NaN,NaN,NaN,NaN
1,2024-03-01,20252968.80,20147364.53,1.984638e+07,0.005242,0.524159,NaN,NaN,0.52
2,2024-04-01,21798729.53,20252968.80,2.073302e+07,0.076323,7.632267,2.073302e+07,NaN,7.63
3,2024-05-01,28693060.33,21798729.53,2.358159e+07,0.316272,31.627214,2.358159e+07,NaN,31.63
4,2024-06-01,29699192.07,28693060.33,2.673033e+07,0.035065,3.506533,2.673033e+07,NaN,3.51

In [15]:
forecast_metrics.to_csv("forecast_metrics_powerbi.csv", index=False)

In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("../data/cleaned/cleaned_procurement.csv")

In [18]:
df.columns

Index(['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category',
       'Order_Status', 'Quantity', 'Unit_Price', 'Negotiated_Price',
       'Defective_Units', 'Compliance', 'Delivery_Missing',
       'Delivery_Delay_Days', 'Savings_Per_Unit', 'Total_Savings',
       'Defect_Rate'],
      dtype='object')

In [19]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], errors='coerce')

In [20]:
df['Month'] = df['Order_Date'].dt.to_period('M').astype(str)

df[['Order_Date', 'Month']].head()

  Order_Date    Month
0 2023-10-17  2023-10
1 2022-04-25  2022-04
2 2022-01-26  2022-01
3 2022-10-09  2022-10
4 2022-09-08  2022-09

In [21]:
df['Spend'] = df['Quantity'] * df['Negotiated_Price']

df[['Quantity', 'Negotiated_Price', 'Spend']].head()

   Quantity  Negotiated_Price      Spend
0      1176             17.81   20944.56
1      1509             37.34   56346.06
2       910             92.26   83956.60
3      1344             95.52  128378.88
4      1180             60.53   71425.40

In [22]:
supplier_metrics = df.groupby('Supplier').agg({
    'Spend': 'sum',
    'Delivery_Delay_Days': 'mean',
    'Defect_Rate': 'mean',
    'Compliance': lambda x: (x == 'YES').mean() * 100
}).reset_index()

In [23]:
supplier_metrics.columns = [
    'Supplier',
    'Total_Spend',
    'Avg_Delivery_Delay',
    'Avg_Defect_Rate',
    'Compliance_Rate'
]

supplier_metrics.head()

,Supplier,Total_Spend,Avg_Delivery_Delay,Avg_Defect_Rate,Compliance_Rate
0,ALPHA_INC,7839712.25,10.606838,0.018905,93.617021
1,BETA_SUPPLIES,9858665.90,11.272727,0.082723,75.641026
2,DELTA_LOGISTICS,9236240.47,10.854305,0.108666,60.818713
3,EPSILON_GROUP,9851156.06,10.865772,0.026063,98.192771
4,GAMMA_CO,8587921.71,10.192308,0.044975,86.013986

In [24]:
supplier_metrics.to_csv("supplier_metrics_powerbi.csv", index=False)

In [25]:
category_metrics = df.groupby(['Month', 'Item_Category']).agg({
    'Spend': 'sum',
    'Total_Savings': 'sum',
    'Quantity': 'sum'
}).reset_index()

In [26]:
category_metrics.columns = [
    'Month',
    'Category',
    'Total_Spend',
    'Total_Savings',
    'Total_Quantity'
]

category_metrics.head()

     Month         Category  Total_Spend  Total_Savings  Total_Quantity
0  2022-01      ELECTRONICS    457394.75       44878.58           10546
1  2022-01              MRO    219508.07       13005.16            3693
2  2022-01  OFFICE SUPPLIES    355703.42       33250.99            6234
3  2022-01        PACKAGING    232816.41       18622.53            5753
4  2022-01    RAW MATERIALS    270956.28       34598.07            6328

In [27]:
category_metrics.to_csv("category_metrics_powerbi.csv", index=False)

In [28]:
high_risk_suppliers = supplier_metrics[
    (supplier_metrics['Total_Spend'] > supplier_metrics['Total_Spend'].mean()) &
    (
        (supplier_metrics['Avg_Delivery_Delay'] > supplier_metrics['Avg_Delivery_Delay'].mean()) |
        (supplier_metrics['Avg_Defect_Rate'] > supplier_metrics['Avg_Defect_Rate'].mean())
    )
]

In [29]:
high_risk_suppliers.to_csv("high_risk_suppliers.csv", index=False)

high_risk_suppliers.head()

,Supplier,Total_Spend,Avg_Delivery_Delay,Avg_Defect_Rate,Compliance_Rate
1,BETA_SUPPLIES,9858665.90,11.272727,0.082723,75.641026
2,DELTA_LOGISTICS,9236240.47,10.854305,0.108666,60.818713
3,EPSILON_GROUP,9851156.06,10.865772,0.026063,98.192771

In [30]:
supplier_metrics.to_csv("supplier_metrics_powerbi.csv", index=False)

In [31]:
category_metrics = df.groupby(['Month', 'Item_Category']).agg({
    'Spend': 'sum',
    'Total_Savings': 'sum',
    'Quantity': 'sum'
}).reset_index()

In [32]:
category_metrics.columns = [
    'Month',
    'Category',
    'Total_Spend',
    'Total_Savings',
    'Total_Quantity'
]

category_metrics.head()

     Month         Category  Total_Spend  Total_Savings  Total_Quantity
0  2022-01      ELECTRONICS    457394.75       44878.58           10546
1  2022-01              MRO    219508.07       13005.16            3693
2  2022-01  OFFICE SUPPLIES    355703.42       33250.99            6234
3  2022-01        PACKAGING    232816.41       18622.53            5753
4  2022-01    RAW MATERIALS    270956.28       34598.07            6328

In [33]:
category_metrics.to_csv("category_metrics_powerbi.csv", index=False)

In [34]:
high_risk_suppliers = supplier_metrics[
    (supplier_metrics['Total_Spend'] > supplier_metrics['Total_Spend'].mean()) &
    (
        (supplier_metrics['Avg_Delivery_Delay'] > supplier_metrics['Avg_Delivery_Delay'].mean()) |
        (supplier_metrics['Avg_Defect_Rate'] > supplier_metrics['Avg_Defect_Rate'].mean())
    )
]

high_risk_suppliers.head()

,Supplier,Total_Spend,Avg_Delivery_Delay,Avg_Defect_Rate,Compliance_Rate
1,BETA_SUPPLIES,9858665.90,11.272727,0.082723,75.641026
2,DELTA_LOGISTICS,9236240.47,10.854305,0.108666,60.818713
3,EPSILON_GROUP,9851156.06,10.865772,0.026063,98.192771

In [35]:
high_risk_suppliers.to_csv("high_risk_suppliers.csv", index=False)

In [36]:
import os

os.listdir()

['.ipynb_checkpoints',
 '01_data_understanding.ipynb',
 '02_exploratory_analysis.ipynb',
 '03_feature_engineering.ipynb',
 '04_predictive_modeling.ipynb',
 '05_sql_validation.ipynb',
 '06_powerbi_metrics_prep.ipynb',
 'category_metrics_powerbi.csv',
 'category_summary.csv',
 'defect_analysis.csv',
 'delay_analysis.csv',
 'forecast_metrics_powerbi.csv',
 'high_risk_suppliers.csv',
 'supplier_metrics_powerbi.csv',
 'supplier_risk_score.csv',
 'supplier_spend.csv']